# Generated by Django 5.2.12 on 2026-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0004_event_album_public_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="guest_upload_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Si False, les invités ne peuvent plus envoyer de médias sur cet album (QR / page album).",
            ),
        ),
    ]
