# Generated by Django 5.2.12 on 2026-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evenements", "0005_album_guest_upload_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFaceEncoding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("embedding", models.JSONField(default=list)),
                ("embedding_dim", models.PositiveSmallIntegerField(default=128)),
                ("quality_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="face_encoding",
                        to="evenements.media",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mediafaceencoding",
            index=models.Index(fields=["created_at"], name="evenements__created_5e1735_idx"),
        ),
    ]
